name: Auto Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.46.215.64 >> ~/.ssh/known_hosts

      - name: Deploy to Kubernetes
        run: |
          ssh root@192.46.215.64 << 'EOF'
            cd /root/nginx-k8s-autodeploy
            git pull origin main
            export KUBECONFIG=/root/my-k8s-cluster-kubeconfig.yaml
            kubectl apply -f manifest/nginx-deployment.yaml
            kubectl apply -f manifest/nginx-service.yaml
          EOF
